### ISSUE TITLE
Tools: write a method to get all the venues

### ISSUE THREAD

**Issue by melisabok** [iesl/openreview-py#128]
It could be all the members of the host groups or all the groups that contains a submission invitation?

**Comment by melisabok** [comment]
This represents the same call that we need for: https://dev.openreview.net/venues

**Comment by mspector** [comment]
it looks like that call is returning some HTML. are we looking for a list of strings, where each string represents a venue? if so, @mohituniyal 's function is doing what we want, but it still does seem like we could just call client.get_group('host') and then get the members.

or maybe are we looking for a list of openreview.Group objects?
