### ISSUE TITLE
Create an instance of Client class without username/password

### ISSUE THREAD

**Issue by melisabok** [iesl/openreview-py#130]
This will be a guest user, no token needed. 

If not parameter set and not environment variable then create the client without a token.

**Comment by mspector** [comment]
This may deserve its own issue, but it might also be a good idea to start thinking about more conventional ways of storing user credentials. Is storing them in environment variables secure enough? I'm not sure. 

I've also been thinking lately that the current way of logging in might leave the user's password too exposed (if not stored in environment variables, the user has to type their credentials in plain text in the python code).

**Comment by melisabok** [comment]
I think we should remove the environment variables.

**Comment by mohituniyal** [comment]
Resolved with #137
