### ISSUE TITLE
Expose the login method as a public method

### ISSUE THREAD

**Issue by melisabok** [iesl/openreview-py#131]
Shouldn't be a private method:

POST /login 

is part of the API and should be public.

**Comment by mohituniyal** [comment]
Just to confirm, we want **Client** class's private method **__login_user(self.username, self.password)** to be publicly accessible?

**Comment by melisabok** [comment]
Yes, I think it should be public. 

If the user doesn't send the username/password when it creates the Client instance then it can login later. 

This is issue is related to #130

**Comment by mohituniyal** [comment]
Resolved with #137
