### ISSUE TITLE
Implement create_note, create_group, create_invitation

### ISSUE THREAD

**Issue by melisabok** [iesl/openreview-py#132]
create an object should be different than post it (update it). 

There are a lot of properties that are set by the server and shouldn't be set in the creation, for example: id of the note. 

An example of create a note:

```
create_note(invitation, readers, writers, signatures, content)
```
returns an instance of a Note

or group:

```
create_group(id, readers, writers, signatories, signatures, web_file_path = None)
```
and return an instance of a Groups and group.web is the content of the file.

**Comment by mspector** [comment]
just to clarify, does `create_note` send the note to the server, or does it just create the openreview.Note object?

so it would be something like:

```
>>> my_note = openreview.create_note( ... )
>>> my_note_posted = client.post_note(my_note)
```

If so, what's the advantage of this over just creating the note object from the constructor? or maybe I'm misunderstanding?

**Comment by melisabok** [comment]
I'm thinking that for the creation of document we don't need to use the class Note. Because the document is incomplete, a lot of properties are being set by the server: id, tcdate, tmdate, tauthor.

**Comment by melisabok** [comment]
I will close this issue, it is not necessary now.

**Comment by mspector** [comment]
What made you change your mind? Or do you just want to do it later?

**Comment by melisabok** [comment]
I think we don't need it right now, I need to think more about it.
