### ISSUE TITLE
PDF: implement how to upload and get a pdf file

### ISSUE THREAD

**Issue by melisabok** [iesl/openreview-py#139]
the HTTP calls are:

```
PUT /pdf
```

and 

```
GET /pdf?id=noteId
```

**Comment by mohituniyal** [comment]
Regarding the get_pdf python implementation, what do we want to do with the pdf once we get it in response? One suggestion is to save it locally i.e. the current directory.

Also, what do we want this method to return? We could return the path to where it is being saved.

@melisabok @mspector  what do you think?

**Comment by melisabok** [comment]
Could we return a PDFFileReader or something similar? 

Then the user can decide what to do, save in the file system, etc

There are some pdf libraries or we can use just some python native code that handles files

**Comment by mohituniyal** [comment]
We can return the raw content of the pdf and the user can utilize that.
>>>c = openreview.Client(baseurl=<URL>)
>>> fd = open('./local_tmp.pdf','wb')
>>> fd.write(c.get_pdf(id=<note-id>))
>>> fd.close()

I checked and found that this writes a pdf perfectly.
