### ISSUE TITLE
Builder: consoles for double blind on homepage

### ISSUE THREAD

**Issue by pmandler** [iesl/openreview-py#219]
Before the blind submissions are created (in other words before submission closed) then the consoles aren't showing up on the homepage.  Tested for PCs and authors.

#!/usr/bin/python

import openreview

def get_conference(client):

    builder = openreview.conference.ConferenceBuilder(client)

    builder.set_conference_id('icaps-conference.org/ICAPS/Workshop/HSDIP')
    builder.set_conference_name('Heuristics and Search for Domain-independent Planning')
    builder.set_conference_short_name('ICAPS HSDIP 2019')
    builder.set_homepage_header({
    'title': 'Heuristics and Search for Domain-independent Planning',
    'subtitle': 'ICAPS 2019 Workshop',
    'deadline': 'Submission Deadline: March 15, 2019',
    'date': 'July 11-15, 2019',
    'website': 'https://icaps19.icaps-conference.org/workshops/HSDIP/index.html',
    'location': 'Berkeley, CA, USA'
    })
    builder.set_double_blind(True)

    return builder.get_result()

import argparse
import openreview
from openreview import tools
from openreview import invitations
import config
import datetime

"""
OPTIONAL SCRIPT ARGUMENTS

	baseurl -  the URL of the OpenReview server to connect to (live site: https://openreview.net)
 	username - the email address of the logging in user
	password - the user's password
"""

parser = argparse.ArgumentParser()
parser.add_argument('--baseurl', help="base URL")
parser.add_argument('--username')
parser.add_argument('--password')

args = parser.parse_args()

client = openreview.Client(baseurl=args.baseurl, username=args.username, password=args.password)
print('connecting to {0}'.format(client.baseurl))

conference = config.get_conference(client)
conference.open_submissions(due_date = datetime.datetime(2019, 3, 15, 23, 59))

**Comment by melisabok** [comment]
Can I close this?

**Comment by pmandler** [comment]
yes
