### ISSUE TITLE
Conference.get_submissions doesn't filter accepted submissions properly

### ISSUE THREAD

**Issue by tvercaut** [iesl/openreview-py#316]
I just saw the recent commit (a3b3b90c17ad1fffd48b9cafaedda6d344427007) to ease getting all accepted submissions:
https://github.com/iesl/openreview-py/blob/a3b3b90c17ad1fffd48b9cafaedda6d344427007/openreview/conference/builder.py#L302

This currently doesn't seem to work for me:
```
>>> print(len(conference.get_submissions(accepted=True)))
0
>>> print(len(conference.get_submissions(accepted=False)))
115
```

The code I use is as such:
```python
#!/usr/bin/env python3

## Import statements
import argparse
import csv
import sys
from openreview import *
import httpimport
import pylatex.utils

## Import statements and argument handling
parser = argparse.ArgumentParser()
parser.add_argument('--cpath', help="conference path ex. MyConf.org/2017", default="MIDL.io/2019/Conference/")
parser.add_argument('--baseurl', help="base url", default="https://openreview.net")
parser.add_argument('--username', required=True)
parser.add_argument('--password', required=True)
args = parser.parse_args()

## Initialize the client library with username and password
client = Client(baseurl=args.baseurl, username=args.username, password=args.password)

## get conference directory
base_path = "https://raw.githubusercontent.com/iesl/openreview-scripts/master/venues/"+args.cpath
config_path = base_path+"/python/"
config_url = config_path+"config.py"

## load conference specific config
print("Loading "+config_url)
with httpimport.remote_repo(['config'], config_path):
    import config

## get the conference object
conference = config.get_conference(client)
print('Retrieved ' + conference.get_submission_id())

print(len(conference.get_submissions(accepted=True)))
print(len(conference.get_submissions(accepted=False)))
```

**Comment by tvercaut** [comment]
If I manually force
```python
conference.legacy_invitation_id = True
```
it then seems to work. Shouldn't `conference.legacy_invitation_id` be set automatically by:
https://github.com/iesl/openreview-scripts/blob/master/venues/MIDL.io/2019/Conference/Abstract/python/config.py
?

**Comment by melisabok** [comment]
By the time we added this property to the library we didn't update the script because it was a one time run script. We don't keep backward compatibility in the openreview-scripts repo. 

The best way to get the accepted papers is using this example:

https://openreview-py.readthedocs.io/en/latest/workshop.html#retrieving-all-accepted-submissions-for-a-conference

**Comment by tvercaut** [comment]
Thanks. I am thus closing this.
